name: Waka Readme

on:
  schedule:
    # Runs at 02.45 am UTC or 06.00  UTC+8 
    - cron: '0 06 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_EDITORS: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_COMMIT: "true"
          SHOW_LANGUAGE: "true"
          SHOW_OS: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_PROJECTS: "false"
          SHOW_LOC_CHART: "true"          
