name: Waka Readme

on:
  push:
    branches: [main]
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  
  workflow_dispatch:

jobs:
   update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "false"
          SHOW_TIMEZONE: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_EDITORS: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_COMMIT: "true"
          SHOW_LANGUAGE: "true"
          SHOW_OS: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_PROJECTS: "false"
          SHOW_LOC_CHART: "true"
