name: README STATS UPDATE

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  push:
    branches:
      - main

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: WakaTime Readme Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_LINES_OF_CODE: "false"
          SHOW_EDITORS: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_COMMIT: "true"
          SHOW_LANGUAGE: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_LOC_CHART: "true"
          SHOW_PROJECTS: "true"
          SHOW_PROFILE_VIEWS: "true"
