# name: README STATS UPDATE

# on:
#   schedule:
#     - cron: '0 0 * * *'  # Runs every day at midnight
#   push:
#     branches:
#       - main

# jobs:
#   update-readme:
#     name: Update Readme with Metrics
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check for Empty Language Data
#         run: |
#           if [ -z "$(curl -s -H "Authorization: Bearer ${{ secrets.WAKATIME_API_KEY }}" "https://wakatime.com/api/v1/users/current/stats/last_7_days" | jq '.data.languages')" ]; then
#             echo "No language data found."
#             echo "languages = []" > empty_languages.json
#           fi

#       - name: WakaTime Readme Stats
#         if: ${{ always() }}
#         uses: anmol098/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           SHOW_OS: "true"
#           SHOW_TIMEZONE: "true"
#           SHOW_SHORT_INFO: "true"
#           SHOW_LINES_OF_CODE: "true"
#           SHOW_TOTAL_CODE_TIME: "true"
#           SHOW_EDITORS: "true"
#           SHOW_DAYS_OF_WEEK: "true"
#           SHOW_COMMIT: "true"
#           SHOW_LANGUAGE: "true"
#           SHOW_LANGUAGE_PER_REPO: "true"
#           SHOW_LOC_CHART: "true"
#           SHOW_PROJECTS: "false"
#           SHOW_PROFILE_VIEWS: "true"
#           DEBUG_LOGGING: "true"

name: README STATS UPDATE

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  push:
    branches: [ main ]

jobs:
   update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_EDITORS: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_COMMIT: "true"
          SHOW_LANGUAGE: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_LOC_CHART: "true"
          SHOW_PROJECTS: "false"
          SHOW_PROFILE_VIEWS: "true"
          DEBUG_LOGGING: "true"
